#!/usr/bin/env python3
"""Generate the command-table Markdown block from each command's frontmatter.

Reads `summary` and `signature` from every `plugins/playwright-scenarios/commands/*.md`
frontmatter and emits a Markdown table to stdout. Use it to populate any doc
surface that needs to list the commands.

Usage:
    scripts/gen-command-table.py                     # default 2-column table
    scripts/gen-command-table.py --order=README      # README-style ordering
    scripts/gen-command-table.py --inplace FILE      # rewrite FILE between markers

Marker convention for in-place updates:
    <!-- COMMANDS:BEGIN -->
    ...generated content...
    <!-- COMMANDS:END -->

The order argument selects a presentation ordering. README mirrors the order
the README has used historically (creation commands first, then pipeline,
then config); USAGE mirrors USAGE.md's existing grouping. Add new orderings
here as new surfaces adopt the generator.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
COMMANDS_DIR = REPO_ROOT / "plugins" / "playwright-scenarios" / "commands"

ORDERINGS = {
    "README": [
        "record-scenario",
        "crawl-site",
        "doc-to-scenarios",
        "generate-fixture",
        "review-scenario",
        "scenario-to-tests",
        "scenario-status",
        "playwright-scenarios-config",
        "scaffold-base-test",
    ],
    "USAGE": [
        "record-scenario",
        "crawl-site",
        "doc-to-scenarios",
        "generate-fixture",
        "review-scenario",
        "scenario-to-tests",
        "scenario-status",
        "playwright-scenarios-config",
        "scaffold-base-test",
    ],
}

BEGIN_MARKER = "<!-- COMMANDS:BEGIN -->"
END_MARKER = "<!-- COMMANDS:END -->"


def parse_frontmatter(path: Path) -> dict[str, str]:
    """Extract simple key: value pairs from a Markdown file's YAML frontmatter.

    Only flat top-level scalar fields are supported (the fields we care about
    are name, description, summary, signature). Multiline scalars and nested
    structures (like the `arguments` array) are skipped.
    """
    text = path.read_text()
    match = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not match:
        raise ValueError(f"{path}: missing or unterminated YAML frontmatter")
    body = match.group(1)
    fields: dict[str, str] = {}
    for line in body.splitlines():
        if not line or line.startswith(("#", " ", "\t", "-")):
            continue
        key, sep, value = line.partition(":")
        if not sep:
            continue
        key = key.strip()
        value = value.strip()
        # Strip surrounding single or double quotes if the value is fully wrapped.
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
            value = value[1:-1].replace(value[0] * 2, value[0])
        fields[key] = value
    return fields


def load_commands() -> dict[str, dict[str, str]]:
    """Load every command's frontmatter, keyed by command name."""
    commands: dict[str, dict[str, str]] = {}
    for path in sorted(COMMANDS_DIR.glob("*.md")):
        fields = parse_frontmatter(path)
        name = fields.get("name")
        if not name:
            raise ValueError(f"{path}: missing `name` in frontmatter")
        for required in ("summary", "signature"):
            if not fields.get(required):
                raise ValueError(f"{path}: missing `{required}` in frontmatter")
        commands[name] = fields
    return commands


def escape_cell(text: str) -> str:
    """Escape pipes so they don't terminate a Markdown table cell."""
    return text.replace("|", r"\|")


DO_NOT_EDIT_NOTICE = (
    "<!-- Generated by scripts/gen-command-table.py — do not edit by hand. -->\n"
    "<!-- Source: plugins/playwright-scenarios/commands/*.md frontmatter "
    "(`summary`, `signature`). -->"
)


def render_table(commands: dict[str, dict[str, str]], order: str) -> str:
    """Render a 2-column Markdown table: signature → summary."""
    if order not in ORDERINGS:
        raise ValueError(f"Unknown order: {order}. Choose from {sorted(ORDERINGS)}")
    lines = [DO_NOT_EDIT_NOTICE, "| Command | Description |", "|---------|-------------|"]
    missing = []
    for name in ORDERINGS[order]:
        if name not in commands:
            missing.append(name)
            continue
        fields = commands[name]
        signature = escape_cell(fields["signature"])
        summary = escape_cell(fields["summary"])
        lines.append(f"| `{signature}` | {summary} |")
    if missing:
        raise ValueError(
            f"Order `{order}` references commands not found on disk: {missing}. "
            "Either add the command file or remove the entry from ORDERINGS."
        )
    extra = sorted(set(commands) - set(ORDERINGS[order]))
    if extra:
        raise ValueError(
            f"Commands on disk but not listed in order `{order}`: {extra}. "
            "Add them to ORDERINGS in scripts/gen-command-table.py."
        )
    return "\n".join(lines)


def update_inplace(path: Path, generated: str) -> bool:
    """Replace the content between BEGIN/END markers in `path`. Returns True if changed."""
    text = path.read_text()
    pattern = re.compile(
        rf"({re.escape(BEGIN_MARKER)}\n).*?(\n{re.escape(END_MARKER)})",
        re.DOTALL,
    )
    if not pattern.search(text):
        raise ValueError(
            f"{path}: missing markers. Insert these around the table:\n"
            f"  {BEGIN_MARKER}\n  ...table...\n  {END_MARKER}"
        )
    new_text = pattern.sub(rf"\g<1>{generated}\g<2>", text)
    if new_text == text:
        return False
    path.write_text(new_text)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--order",
        default="README",
        choices=sorted(ORDERINGS),
        help="Which presentation ordering to use (default: README).",
    )
    parser.add_argument(
        "--inplace",
        type=Path,
        help="Rewrite this file between <!-- COMMANDS:BEGIN --> markers.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="With --inplace, exit 1 if the file would change. Useful for CI.",
    )
    args = parser.parse_args()

    commands = load_commands()
    table = render_table(commands, args.order)

    if args.inplace is None:
        print(table)
        return 0

    path = args.inplace.resolve()
    if args.check:
        original = path.read_text()
        update_inplace(path, table)
        changed = path.read_text() != original
        if changed:
            # Roll back the file so --check doesn't mutate.
            path.write_text(original)
            print(f"{path}: would change (run without --check to apply)", file=sys.stderr)
            return 1
        return 0

    changed = update_inplace(path, table)
    print(f"{path}: {'updated' if changed else 'no change'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
